# DiscordWhitelist plugin created by Rude Yeti, Incorporated.
# A simple plugin which allows synchronization from a Discord Channel
# to a Minecraft Server, whitelisting the provided player names.
# This depends on DiscordSRV, a requirement for this plugin to work.

# General Configuration

# The command used to determine if Minecraft and Discord Accounts are linked.
# Default value: "!check"
command: "!check"

# The ID of the Discord Channel being used as a whitelist.
# Default value: "##################"
channel-id: "##################"

# Whether to link the accounts through DiscordSRV when whitelisting.
# Default value: true
link-accounts: true