# DiscordWhitelist plugin created by Rude Yeti, Incorporated.
# A simple plugin which allows synchronization from a Discord Channel
# to a Minecraft Server, whitelisting the provided player names.
# This depends on DiscordSRV, a requirement for this plugin to work.

# General Configuration

# The command used to determine if Minecraft and Discord Accounts are linked.
# Default value: "!check"
command: "!check"

# The ID of the Discord Channel being used as a whitelist.
# Default value: "##################"
channel-id: "##################"

# Whether to link the accounts through DiscordSRV when whitelisting.
# Default value: true
link-accounts: true

# Whether to delete the whitelist message when a user leaves the Discord Server.
# If this is set to false, then a red x appears on the message instead.
# Default value: true
delete-on-leave: true

# A blacklist of usernames not allowed to be in the whitelist.
# Default value: - ""
blacklist:
  - ""
